import React,{createContext,useContext,useState,useEffect,useRef} from 'react';
import {CartItem,Product,Coupon} from '../types';
import {apiService,get,put} from '../services/api';
import {useToast} from './ToastContext';
import {useAuth} from './AuthContext';
interface CartContextType{items:CartItem[];itemCount:number;subtotal:number;discount:number;shippingFee:number;total:number;appliedCoupon:Coupon|null;addItem:(p:Product,q?:number,s?:string,m?:string)=>void;updateQuantity:(id:string,q:number,s?:string,m?:string)=>void;removeItem:(id:string,s?:string,m?:string)=>void;clearCart:()=>void;applyCoupon:(code:string)=>Promise<boolean>;removeCoupon:()=>void;}
const Context=createContext<CartContextType|undefined>(undefined);const guestKey='jewelry_guest_cart';const key=(i:CartItem)=>JSON.stringify([i.product._id,i.selectedSize||i.size||'',i.selectedMaterial||i.product.material||'']);
export const CartProvider=({children}:{children:React.ReactNode})=>{
 const {user,isLoading}=useAuth(),{showToast}=useToast();const [items,setItems]=useState<CartItem[]>([]),[coupon,setCoupon]=useState<Coupon|null>(null),[ready,setReady]=useState(false),[cfg,setCfg]=useState({shippingFee:150000,freeShipping:50000000,vatRate:0});const owner=useRef<string|null>(null);const saveChain=useRef(Promise.resolve());const lastSaved=useRef('');
 useEffect(()=>{get('/config').then(r=>setCfg(r.data)).catch(()=>{});},[]);
 useEffect(()=>{if(isLoading)return;let live=true;setReady(false);setCoupon(null);owner.current=user?._id||null;
 const load=async()=>{try{let guest:CartItem[]=[];try{guest=JSON.parse(localStorage.getItem(guestKey)||'[]');}catch{}let next=guest;if(user){const remote=(await get('/cart')).data;const merged=new Map<string,CartItem>();for(const item of [...remote,...guest]){const k=key(item);const old=merged.get(k);merged.set(k,old?{...item,quantity:Math.min(item.product.stock,old.quantity+item.quantity)}:item);}next=[...merged.values()];if(guest.length){next=(await put('/cart',{items:next})).data;localStorage.removeItem(guestKey);}}if(live){lastSaved.current=JSON.stringify(next);setItems(next);setReady(true);}}catch(e:any){if(live){setItems([]);showToast(e.message,'error');}}};load();return()=>{live=false;};},[user?._id,isLoading]);
 useEffect(()=>{if(!ready)return;const serialized=JSON.stringify(items);if(!user){localStorage.setItem(guestKey,serialized);return;}if(serialized===lastSaved.current)return;const uid=user._id;const timer=setTimeout(()=>{saveChain.current=saveChain.current.then(async()=>{if(owner.current!==uid)return;try{await put('/cart',{items});lastSaved.current=serialized;}catch(e:any){showToast('Chưa lưu được giỏ hàng: '+e.message,'error');}});},200);return()=>clearTimeout(timer);},[items,ready,user?._id]);
 const addItem=(product:Product,quantity=1,size?:string,material?:string)=>{if(!ready){showToast('Giỏ hàng đang tải, vui lòng thử lại','info');return;}if(!Number.isInteger(quantity)||quantity<1||product.status!=='active'||product.stock<=0){showToast('Sản phẩm không khả dụng','error');return;}const selectedSize=size||product.size||product.availableSizes?.[0],selectedMaterial=material||product.material;const variants=(product as any).variants||[];const variant=variants.find((v:any)=>(v.size||'')===(selectedSize||'')&&(v.material||product.material)===selectedMaterial);if(variants.length&&!variant){showToast('Vui lòng chọn đúng biến thể','error');return;}const max=variant?variant.stock:product.stock;const entry={product:variant?{...product,price:variant.price,salePrice:undefined,stock:max}:product,quantity,selectedSize,selectedMaterial};const k=key(entry);const used=items.filter(i=>key(i)===k).reduce((s,i)=>s+i.quantity,0);if(used+quantity>max){showToast(`Chỉ còn ${max} sản phẩm cho lựa chọn này`,'error');return;}setItems(prev=>{const existing=prev.find(i=>key(i)===k);return existing?prev.map(i=>key(i)===k?{...i,quantity:i.quantity+quantity}:i):[...prev,entry];});showToast('Đã thêm vào giỏ hàng','success');};
 const matches=(i:CartItem,id:string,s?:string,m?:string)=>i.product._id===id&&(i.selectedSize||i.size||'')===(s||'')&&(m===undefined||(i.selectedMaterial||i.product.material||'')===m);
 const removeItem=(id:string,s?:string,m?:string)=>setItems(prev=>prev.filter(i=>!matches(i,id,s,m)));
 const updateQuantity=(id:string,q:number,s?:string,m?:string)=>{if(q<=0){removeItem(id,s,m);return;}if(!Number.isInteger(q))return;setItems(prev=>prev.map(i=>matches(i,id,s,m)?{...i,quantity:Math.min(q,i.product.stock)}:i));};
 const subtotal=items.reduce((s,i)=>s+(i.product.salePrice??i.product.price)*i.quantity,0);let discount=coupon&&subtotal>=coupon.minOrderValue?(coupon.discountType==='percentage'?Math.round(subtotal*coupon.discountValue/100):coupon.discountValue):0;if(coupon?.maxDiscount)discount=Math.min(discount,coupon.maxDiscount);discount=Math.min(subtotal,discount);const shippingFee=items.length?(subtotal>=cfg.freeShipping?0:cfg.shippingFee):0;const total=subtotal-discount+Math.round((subtotal-discount)*cfg.vatRate/100)+shippingFee;
 const clearCart=()=>{setItems([]);setCoupon(null);localStorage.removeItem(guestKey);if(user){saveChain.current=saveChain.current.then(async()=>{await put('/cart',{items:[]});lastSaved.current='[]';}).catch(e=>showToast(e.message,'error'));}};
 const applyCoupon=async(code:string)=>{try{const r=await apiService.coupons.check(code,subtotal);setCoupon(r.data.coupon);showToast('Đã áp dụng mã giảm giá','success');return true;}catch(e:any){showToast(e.message,'error');return false;}};
 return <Context.Provider value={{items,itemCount:items.reduce((s,i)=>s+i.quantity,0),subtotal,discount,shippingFee,total,appliedCoupon:coupon,addItem,updateQuantity,removeItem,clearCart,applyCoupon,removeCoupon:()=>setCoupon(null)}}>{children}</Context.Provider>;
};
export const useCart=()=>{const c=useContext(Context);if(!c)throw new Error('CartProvider required');return c;};
